/**
 * Traductions anglaises des ARTICLES, indexées par le texte français d'origine.
 *
 * Séparé de `i18n-en.ts`, qui porte les phrases de l'interface : la prose d'un
 * article se compte en milliers de caractères et noierait le reste. Le mécanisme
 * est le même, une phrase absente reste en français.
 *
 * Fichier ENGENDRÉ, ne pas modifier à la main : les clés sont relues depuis les
 * blocs en base pour qu'elles correspondent au caractère près. L'anglais s'écrit
 * dans `scripts/gen-i18n-article-overlay.mts`, puis on relance ce script.
 */
export const EN_ARTICLES: Record<string, string> = {
  "Comment streamer une partie de Riftbound avec un téléphone":
    "How to stream a Riftbound game with a phone",
  "Un téléphone filme la table, les joueurs comptent leurs points sur un second appareil et l'overlay se met à jour. Voici le matériel et les réglages nécessaires.":
    "One phone films the table, the players track points on a second device, and the overlay updates. Here is the gear and setup you need.",
  "L'overlay du site permet de filmer une partie avec OBS. Pour un tournoi en boutique ou une partie entre amis, un PC, une caméra et un second écran prennent vite trop de place.\n\nCette nouvelle version tient sur deux appareils : un téléphone sur un trépied filme la table et affiche l'overlay ; une tablette, ou un vieux téléphone, reste entre les joueurs pour compter les points. Les joueurs gèrent leur match, le score suit à l'écran et vous pouvez vous concentrer sur le direct.":
    "The site's overlay lets you stream a game with OBS. At a local tournament or a game with friends, a PC, a camera and a second screen quickly take up too much room.\n\nThis new version runs on two devices: a phone on a tripod films the table and displays the overlay; a tablet, or an old phone, sits between the players to track points. The players manage their match, the score updates on stream, and you can focus on the broadcast.",
  "Le téléphone filme la table pendant que les joueurs comptent leurs points sur la tablette.":
    "The phone films the table while the players track their points on the tablet.",
  "## Un overlay prévu pour le téléphone\n\nL'overlay compact garde ce qui aide à suivre la partie : le score, les deux Légendes avec leur champion élu, les champs de bataille, les manches gagnées et la carte affichée. Il retire les cadres caméra, le décor, le chrono et le logo du tournoi.\n\nSon fond transparent se pose sur la vidéo sans cacher le tapis. Les textes restent lisibles sur le petit écran d'un téléphone.":
    "## An overlay made for phones\n\nThe compact overlay keeps what viewers need to follow the game: the score, both Legends with their chosen champion, the battlefields, games won and the card on display. It removes the camera frames, layout, timer and event logo.\n\nIts transparent background sits over the video without hiding the playmat. Text remains readable on a phone's small screen.",
  "Une partie en cours vue du dessus, avec l'overlay compact posé par-dessus.":
    "A game in progress seen from above, with the compact overlay laid over it.",
  "Le score, les Légendes et les champs de bataille restent visibles pendant la partie.":
    "The score, Legends and battlefields remain visible during the game.",
  "Vous pouvez lancer la scène avant de recevoir les decklists. Le cadre des cartes reste vide, puis vous collez chaque liste pendant que les joueurs s'installent.":
    "You can start the scene before receiving the decklists. The card frame stays empty, then you paste each list while the players get ready.",
  "Pendant la partie, un clic affiche une carte de la decklist et un second la retire. La recherche permet aussi de montrer une carte absente des deux decks. Si personne ne pilote le direct, le mode automatique fait défiler les cartes à la vitesse choisie.":
    "During the game, one click shows a card from the decklist and a second hides it. Search also lets you show a card that is in neither deck. If nobody is running the broadcast, automatic mode cycles through the cards at the chosen speed.",
  "Le plateau vide avant le début de la partie, avec les deux Légendes et le score déjà affichés.":
    "The empty table before the game starts, with both Legends and the score already on screen.",
  "Le spectateur voit les deux decks avant le début de la partie.":
    "The viewer sees both decks before the game begins.",
  "## Le compagnon de match\n\nLes joueurs ouvrent un lien, sans compte ni application à installer. Ils choisissent le format, les points requis pour gagner, puis leurs pseudos, leur Légende, leur champion élu et leur champ de bataille. Après le récapitulatif, « Lancer la partie » envoie tout sur l'overlay.\n\nL'écran se partage ensuite dans la longueur. Chaque joueur lit sa moitié à l'endroit depuis sa chaise et change ses points avec deux gros boutons.":
    "## The match companion\n\nPlayers open a link, with no account or app to install. They choose the format, the points needed to win, then their names, Legend, chosen champion and battlefield. After the recap, \"Start the game\" sends everything to the overlay.\n\nThe screen then splits lengthwise. Each player reads their half the right way up from their seat and changes their points with two large buttons.",
  "Le compagnon de match sur une tablette posée à plat entre les deux joueurs, l'écran coupé en deux.":
    "The match companion on a tablet lying flat between the two players, the screen split in two.",
  "Chaque joueur gère ses points depuis son côté de la table.":
    "Each player tracks their points from their side of the table.",
  "À la fin d'une manche, les joueurs touchent « Fin de la manche », indiquent le gagnant et choisissent le champ de bataille suivant. « Annuler la dernière manche » corrige une erreur.\n\nDe votre côté, vous pouvez changer le titre ou la carte affichée sans toucher au score saisi par les joueurs.":
    "At the end of a game, players tap \"End game\", choose the winner and select the next battlefield. \"Undo last game\" fixes a mistake.\n\nOn your side, you can change the title or displayed card without changing the score entered by the players.",
  "Toute personne qui possède le lien du compagnon peut changer le score. Ne montrez pas ce lien en direct et ne le laissez pas dans une capture.":
    "Anyone with the companion link can change the score. Do not show this link on stream or leave it visible in a screenshot.",
  "## Installer l'overlay sur votre téléphone\n\nTout part de la page **[Overlay](/profil/overlay)**, dans votre profil. Connectez-vous avec Discord, et gardez ces deux liens sous la main :\n\n| Lien | À quoi il sert |\n|---|---|\n| L'overlay compact | L'overlay à poser sur l'image de votre téléphone |\n| Le lien compagnon | La version des joueurs, à leur envoyer |\n\n## Préparer le match sur le site\n\nLa page Overlay pilote le direct. Chaque changement est enregistré et envoyé à l'écran aussitôt : il n'y a pas de bouton « Enregistrer ».\n\n1. Ouvrez **Liens et affichage OBS**, puis copiez **l'overlay compact**. C'est cette adresse que vous collerez dans Moblin.\n2. Copiez ensuite le **lien compagnon** et ouvrez-le sur la tablette posée entre les joueurs.\n3. Les joueurs choisissent le format, les points requis pour gagner, leurs pseudos, leurs Légendes, leurs champions élus et leurs champs de bataille. Dès qu'ils touchent **Lancer la partie**, l'overlay reçoit ces données.\n4. Pour montrer des cartes, ouvrez **Cartes à l'écran** dans le tableau de bord. Collez une decklist pour chaque joueur, touchez **Charger**, puis choisissez l'affichage. Un clic sur une carte la montre ; **Diapo auto** les fait défiler.\n\nVous pouvez corriger un pseudo, un score ou une carte depuis le tableau de bord pendant le match. Le compagnon et la page Overlay mettent à jour des parties différentes de l'écran, donc les joueurs peuvent continuer à compter leurs points pendant vos changements.\n\n## Avec Moblin\n\n[Moblin](https://apps.apple.com/app/moblin/id6466745933) est une application gratuite et à code ouvert pour iPhone. Elle filme, diffuse vers Twitch, YouTube ou Kick et peut poser une page web sur la vidéo.\n\nL'overlay compact se charge dans Moblin comme un widget Navigateur transparent. Moblin reçoit une page web en 1920 × 1080, puis l'adapte à la vidéo du téléphone. Il faut donc garder cette taille même si l'écran de l'iPhone a une autre définition.\n\nLe réglage prend six étapes :\n\n1. **Réglages**, puis **Widgets de scène**, puis **Créer**.\n2. Type **Navigateur**, et un nom pour le retrouver.\n3. Collez le lien de l'overlay compact dans le champ **URL**.\n4. Cochez la scène qui filme la table.\n5. Dans les réglages du widget, gardez une largeur de **1920** et une hauteur de **1080** pour ne pas déformer l'overlay.\n6. Vérifiez que le widget est bien allumé dans la scène.\n\nLa vidéo ci-dessous montre les six étapes. L'application y apparaît en anglais car elle suit la langue du téléphone.":
    "## Installing the overlay on your phone\n\nIt all starts on the **[Overlay](/profil/overlay)** page in your profile. Sign in with Discord, and keep these two links within reach:\n\n| Link | What it is for |\n|---|---|\n| The compact overlay | The overlay to lay over your phone's picture |\n| The companion link | The players' side, to send to them |\n\n## Preparing the match on the site\n\nThe Overlay page controls the broadcast. Every change is saved and sent to the screen immediately: there is no Save button.\n\n1. Open **Links and OBS display**, then copy the **compact overlay**. This is the address you will paste into Moblin.\n2. Copy the **companion link**, then open it on the tablet placed between the players.\n3. The players choose the format, points needed to win, their names, Legends, chosen champions and battlefields. As soon as they tap **Start the game**, the overlay receives these details.\n4. To show cards, open **Cards on screen** in the dashboard. Paste one decklist for each player, tap **Load**, then choose the display. Tap a card to show it; **Auto slideshow** cycles through them.\n\nYou can correct a name, score or displayed card from the dashboard during the match. The companion and Overlay page update different parts of the screen, so players can keep tracking points while you make changes.\n\n## With Moblin\n\n[Moblin](https://apps.apple.com/app/moblin/id6466745933) is a free, open-source iPhone app. It films, streams to Twitch, YouTube or Kick, and can place a web page over the video.\n\nThe compact overlay loads in Moblin as a transparent Browser widget. Moblin receives a 1920 × 1080 web page, then scales it to the phone's video. Keep this size even if the iPhone screen uses a different resolution.\n\nSetup takes six steps:\n\n1. **Settings**, then **Scene widgets**, then **Create**.\n2. Type **Browser**, and a name so you can find it again.\n3. Paste the compact overlay link into the **URL** field.\n4. Tick the scene that films the table.\n5. In the widget settings, keep the width at **1920** and height at **1080** so the overlay does not stretch.\n6. Check that the widget is switched on in the scene.\n\nThe video below shows all six steps. The app appears in English because it follows the phone's language.",
  "Le montage complet dans Moblin, de la création du widget jusqu'à l'overlay affiché sur la scène.":
    "The whole setup inside Moblin, from creating the widget to the overlay showing on the scene.",
  "## Sur Android avec IRL Pro\n\n[IRL Pro](https://play.google.com/store/apps/details?id=app.irlpro.android) peut ajouter l'overlay comme une page web au-dessus de la caméra.\n\n1. Ouvrez **Settings**, puis **Overlays** et **Web Overlays**.\n2. Touchez **New web overlay**.\n3. Donnez un nom à l'overlay, puis collez le lien de l'overlay compact dans **URL**.\n4. Dans **WebView options**, réglez la largeur sur **1920**, la hauteur sur **1080** et l'échelle sur **100 %**.\n5. Revenez à la caméra et vérifiez que l'overlay apparaît avant de lancer le direct.":
    "## On Android with IRL Pro\n\n[IRL Pro](https://play.google.com/store/apps/details?id=app.irlpro.android) can add the overlay as a web page over the camera feed.\n\n1. Open **Settings**, then **Overlays** and **Web Overlays**.\n2. Tap **New web overlay**.\n3. Name the overlay, then paste the compact overlay link into **URL**.\n4. Under **WebView options**, set the width to **1920**, height to **1080**, and scale to **100%**.\n5. Return to the camera and check that the overlay appears before going live.",
  "Ajouter l'overlay compact dans IRL Pro, puis contrôler son affichage sur la caméra.":
    "Adding the compact overlay in IRL Pro, then checking it on the camera feed.",
  "## Sur Android avec PRISM Live Studio\n\n[PRISM Live Studio](https://play.google.com/store/apps/details?id=com.prism.live) permet aussi d'ajouter une page web à la scène.\n\n1. Ouvrez **My Studio** depuis l'écran de la caméra.\n2. Touchez **Web**.\n3. Collez le lien de l'overlay compact dans **URL**, ajoutez un titre, puis touchez **Save**.\n4. Placez l'overlay sur toute l'image dans l'éditeur.\n5. Fermez l'éditeur et vérifiez le rendu sur la caméra avant de lancer le direct.":
    "## On Android with PRISM Live Studio\n\n[PRISM Live Studio](https://play.google.com/store/apps/details?id=com.prism.live) can also add a web page to the scene.\n\n1. Open **My Studio** from the camera screen.\n2. Tap **Web**.\n3. Paste the compact overlay link into **URL**, add a title, then tap **Save**.\n4. Fit the overlay to the full frame in the editor.\n5. Close the editor and check the camera view before going live.",
  "Ajouter l'overlay compact dans PRISM Live Studio et l'ajuster à l'image.":
    "Adding the compact overlay in PRISM Live Studio and fitting it to the frame.",
  "Un iPhone sur un petit trépied, qui filme le tapis avec l'overlay compact déjà en place.":
    "An iPhone on a small tripod, filming the playmat with the compact overlay already in place.",
  "Côté caméra, le montage tient dans un téléphone et un trépied.":
    "On the camera side, the setup fits into a phone and a tripod.",
  "## Choisir un support\n\nPour garder une image stable pendant toute la partie, posez le téléphone sur un trépied ou un bras fixé à la table. **Aucun de ces deux liens n'est sponsorisé** : je ne touche rien sur les ventes et les prix peuvent changer.":
    "## Choosing a mount\n\nTo keep the picture steady for the whole game, place the phone on a tripod or an arm clamped to the table. **Neither of these links is sponsored**: I earn nothing from sales and prices may change.",
  "### Sur la table, à côté du tapis\n\nCe petit trépied filme de biais depuis le bord du tapis et tient dans une poche de sac. Il faut ajouter une pince pour téléphone : le modèle porte une vis photo, pas un berceau.":
    "### On the table, beside the playmat\n\nThis small tripod films at an angle from the edge of the playmat and fits in a bag pocket. You need to add a phone clamp: the model has a camera screw, not a cradle.",
  "Manfrotto PIXI, trépied de table":
    "Manfrotto PIXI, tabletop tripod",
  "Un petit trépied à poser au bord du tapis.":
    "A small tripod to place beside the playmat.",
  "Voir sur Amazon":
    "See on Amazon",
  "### Au-dessus du tapis\n\nLa vue du dessus montre mieux la partie, mais demande de suspendre le téléphone sans gêner les joueurs. Ce bras articulé se serre au bord de la table et tient l'iPhone avec un aimant MagSafe. Un anneau magnétique est fourni pour les autres téléphones.":
    "### Above the playmat\n\nA top-down view shows the game better, but requires suspending the phone without getting in the players' way. This articulated arm clamps to the table edge and holds an iPhone with a MagSafe magnet. It includes a magnetic ring for other phones.",
  "UGREEN, bras articulé magnétique":
    "UGREEN, magnetic articulated arm",
  "Se serre au bord de la table, tient le téléphone par aimant.":
    "Clamps to the table edge, holds the phone by magnet.",
};
